-- MySQL Script generated by MySQL Workbench
-- 02/24/18 11:24:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ustedite_tournaments
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ustedite_tournaments
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ustedite_tournaments` DEFAULT CHARACTER SET latin1 ;
USE `ustedite_tournaments` ;

-- -----------------------------------------------------
-- Table `ustedite_tournaments`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ustedite_tournaments`.`players` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(15) NULL,
  `email` VARCHAR(100) NOT NULL,
  `status` INT(1) NULL COMMENT '0 - wait ; 1 - active; 2 - inactive; 3 - invitation mail sent;',
  `password` VARCHAR(50) NULL,
  `passhash` VARCHAR(45) NULL,
  `born` INT(4) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ustedite_tournaments`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ustedite_tournaments`.`games` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ustedite_tournaments`.`platforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ustedite_tournaments`.`platforms` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ustedite_tournaments`.`tournaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ustedite_tournaments`.`tournaments` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `type` INT(1) NULL COMMENT '1 - igraci; 2 - timovi',
  `tournamentgame` INT(5) NULL,
  `platform` INT(5) NULL,
  `tournamenttime` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fktournamentgame_idx` (`tournamentgame` ASC),
  INDEX `fktournamentplatform_idx` (`platform` ASC),
  CONSTRAINT `fktournamentgame`
    FOREIGN KEY (`tournamentgame`)
    REFERENCES `ustedite_tournaments`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fktournamentplatform`
    FOREIGN KEY (`platform`)
    REFERENCES `ustedite_tournaments`.`platforms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ustedite_tournaments`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ustedite_tournaments`.`team` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `capitan_id` INT(5) NULL,
  PRIMARY KEY (`id`),
  INDEX `fkplayerteam_idx` (`capitan_id` ASC),
  CONSTRAINT `fkplayerteam`
    FOREIGN KEY (`capitan_id`)
    REFERENCES `ustedite_tournaments`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ustedite_tournaments`.`tournament_entry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ustedite_tournaments`.`tournament_entry` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `playerid` INT(5) NULL,
  `teamid` INT(5) NULL,
  `tournamentid` INT(5) NOT NULL,
  `status` INT(1) NULL COMMENT '0 - wait verification; 1 - accepted',
  PRIMARY KEY (`id`),
  INDEX `fkteamidentry_idx` (`playerid` ASC),
  INDEX `fktournamentidentry_idx` (`tournamentid` ASC),
  INDEX `fkteamidentry_idx1` (`teamid` ASC),
  CONSTRAINT `fkplayeridentry`
    FOREIGN KEY (`playerid`)
    REFERENCES `ustedite_tournaments`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fktournamentidentry`
    FOREIGN KEY (`tournamentid`)
    REFERENCES `ustedite_tournaments`.`tournaments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkteamidentry`
    FOREIGN KEY (`teamid`)
    REFERENCES `ustedite_tournaments`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ustedite_tournaments`.`results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ustedite_tournaments`.`results` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `matchid` INT(5) NOT NULL,
  `homeval` INT(5) NULL DEFAULT NULL,
  `visitorval` INT(5) NULL DEFAULT NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `tournamentid` INT(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ustedite_tournaments`.`playerteam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ustedite_tournaments`.`playerteam` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `playerid` INT(5) NULL,
  `teamid` INT(5) NOT NULL,
  INDEX `fkplayerteamteam_idx` (`teamid` ASC),
  INDEX `fkplayerteamplayer_idx` (`playerid` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fkplayerteamteam`
    FOREIGN KEY (`teamid`)
    REFERENCES `ustedite_tournaments`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkplayerteamplayer`
    FOREIGN KEY (`playerid`)
    REFERENCES `ustedite_tournaments`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ustedite_tournaments`.`matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ustedite_tournaments`.`matches` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `tournamentid` INT(5) NOT NULL,
  `matchtime` DATETIME NULL DEFAULT NULL,
  `matchid` INT(5) NOT NULL,
  `homematchid` INT(5) NULL,
  `homematchidtype` INT(1) NULL,
  `homeparticipantid` INT(5) NULL,
  `visitormatchid` INT(5) NULL,
  `visitormatchidtype` INT(1) NULL,
  `visitorparticipantid` INT(5) NULL,
  `roundid` INT(5) NULL,
  `timestamp` DATETIME NULL DEFAULT current_timestamp,
  `position` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fkmatchestournaments_idx` (`tournamentid` ASC),
  UNIQUE INDEX `unique` (`tournamentid` ASC, `matchid` ASC),
  CONSTRAINT `fkmatchestournaments`
    FOREIGN KEY (`tournamentid`)
    REFERENCES `ustedite_tournaments`.`tournaments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
